-- V4: Mentions tracking and media metadata

-- Mentions table for efficient "messages mentioning me" queries
CREATE TABLE IF NOT EXISTS message_mentions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id VARCHAR(128) NOT NULL,
  conversation_id VARCHAR(128) NOT NULL,
  sender_user_id VARCHAR(128) NOT NULL,
  mentioned_user_id VARCHAR(128) NOT NULL,
  created_at_epoch_ms BIGINT NOT NULL,
  UNIQUE (message_id, mentioned_user_id)
);

CREATE INDEX IF NOT EXISTS idx_mentions_mentioned_user
  ON message_mentions (mentioned_user_id, created_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_mentions_conversation
  ON message_mentions (conversation_id, created_at_epoch_ms);
