-- Phone number verification and authentication

CREATE TABLE IF NOT EXISTS phone_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verification_id VARCHAR(128) UNIQUE NOT NULL,
  phone_number VARCHAR(32) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  otp_hash VARCHAR(256) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  attempts INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  created_at_epoch_ms BIGINT NOT NULL,
  expires_at_epoch_ms BIGINT NOT NULL,
  verified_at_epoch_ms BIGINT
);

CREATE TABLE IF NOT EXISTS user_phone_numbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(128) UNIQUE NOT NULL,
  phone_number VARCHAR(32) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  verified_at_epoch_ms BIGINT NOT NULL,
  UNIQUE (phone_number, country_code)
);

CREATE INDEX IF NOT EXISTS idx_phone_verifications_phone ON phone_verifications (phone_number, country_code);
CREATE INDEX IF NOT EXISTS idx_phone_verifications_status ON phone_verifications (status, expires_at_epoch_ms);
CREATE INDEX IF NOT EXISTS idx_user_phone_numbers_phone ON user_phone_numbers (phone_number, country_code);
